baseURL = "http://mindabit.chat/"
languageCode = "zh-cn"
title = "Mind a bit | 基智一点"
description = "关于智能基础的一些讨论"
theme = "mindabit-theme"
publishDir = "docs"
[taxonomies]
  category = "categories"
  discipline = "disciplines"
  tag = "tags"
